# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ppt_finder.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from create_index_2 import Ui_Form
from ppt_functions.Powerpoint_find_keyword import PowerPoint_keyword_search
from configs.log_config import get_logger as logger

ppt_finder = PowerPoint_keyword_search()


class Ui_MainWindow(object):
    def index_window(self):
        # HINT 這邊根據create_index檔內的類別進行設定，根據情況會是QDialog or QWidget
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()

    def search_process(self):
        self.plainTextEdit_output.clear()
        text_value = self.plainTextEdit_input.toPlainText()
        print(text_value)
        try:
            result = ppt_finder.find_keyword_from_library(text_value)
            font = QtGui.QFont()
            font.setFamily("微軟正黑體")
            font.setPointSize(12)
            self.plainTextEdit_output.setFont(font)
            self.plainTextEdit_output.insertPlainText(result)
        except FileNotFoundError as e:
            logger().warning(f"ppt_library file not found: {e}")
            QMessageBox.warning(self, "警告", "請先建立索引檔。")
        except Exception as e:
            logger().error(f"search_process failed: {e}, current text_value: {text_value}")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(563, 391)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(466, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(548, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 3)
        self.plainTextEdit_output = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_output.setReadOnly(True)
        self.plainTextEdit_output.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit_output, 6, 0, 1, 3)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.index_window)
        self.gridLayout.addWidget(self.pushButton_2, 0, 2, 2, 1)
        self.plainTextEdit_input = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_input.setFont(font)
        self.plainTextEdit_input.setObjectName("textEdit")
        self.gridLayout.addWidget(self.plainTextEdit_input, 3, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.search_process)
        self.gridLayout.addWidget(self.pushButton, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 563, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "請輸入關鍵字(須先建立索引)"))
        self.pushButton_2.setText(_translate("MainWindow", "建立索引"))
        self.pushButton.setText(_translate("MainWindow", "開始搜尋"))
